name: mikker.github.com
# GitHub defaults
safe: true
lsi: false
pygments: true
# markdown: redcarpet2
permalinks: "/:year/:month/:day/:title/"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
