name: mikker.github.com
description: A place for releasing stuff and explaining gists
url: http://mikker.github.io
# GitHub defaults
safe: true
lsi: false
pygments: true
markdown: redcarpet
permalinks: "/:year/:month/:day/:title/"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
