# Site settings
title: mikker.github.io
email: mikkel@brnbw.com
description: "It's just text."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikker.github.io" # the base hostname & protocol for your site
twitter_username: mikker
github_username:  mikker

# Build settings
kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: false
    inline_theme: github
